#! bin/bash

#Script 08. Nos pide un nombre de fichero. Verifica si existe
#y que es de lectura-escritura. LO convierte en ejecutable para
#el usuario y el grupo. Muestra el estado final de los servicios

if [ -e $1 ]
	then
		if [ -f $1 ]
			then
				echo "$1 existe y es un fichero"
				if [ -r $1 ] && [ -w $1 ]
					then
						echo "Es un fichero de lectura-escritura"
						chmod ug+x $1
						ls -l $1
				else
					echo "No es un fichero de lectura-escritura"
				fi
		else
			echo "$1 existe pero no es un archivo"
		fi
else
	echo "El parametro $1 no existe"
fi
