#! bin/bash

#Script 03. Da un parametro, el script determina si es un archivo o directorio o no existe

if [ $# -ne 1 ]
	then
		echo "Solo se debe pasar 1 parametro"
		exit 1
fi

if [ -e $1 ]
	then
		if [ -f $1 ]
			then
				echo "El parametro es un archivo"

		elif [ -d $2 ]
			then
				echo "El parametro es un directorio"
		else
			echo "El parametro $1 no es un archivo ni directorio"
			exit 1
		fi
else
	echo "No existe $1"
	exit 1
fi
exit 0
